// <auto-generated />
using System;
using Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final.Migrations
{
    [DbContext(typeof(FinalContextGlobal))]
    [Migration("20210724192327_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final.Models.Alojamiento", b =>
                {
                    b.Property<int>("pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barrio")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("baños")
                        .HasColumnType("int");

                    b.Property<int>("cantPersonas")
                        .HasColumnType("int");

                    b.Property<string>("ciudad")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<int>("estrellas")
                        .HasColumnType("int");

                    b.Property<int>("habitaciones")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("precioDia")
                        .HasColumnType("int");

                    b.Property<int>("precioPorPersona")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("tv")
                        .HasColumnType("bit");

                    b.HasKey("pk");

                    b.ToTable("Alojamientos");
                });

            modelBuilder.Entity("Final.Models.Reserva", b =>
                {
                    b.Property<int>("pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fdesde")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fhasta")
                        .HasColumnType("datetime");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("personaint")
                        .HasColumnType("int");

                    b.Property<int?>("personanum_usr")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<int>("propiedadint")
                        .HasColumnType("int");

                    b.Property<int?>("propiedadpk")
                        .HasColumnType("int");

                    b.HasKey("pk");

                    b.HasIndex("personanum_usr");

                    b.HasIndex("propiedadpk");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Final.Models.Usuario", b =>
                {
                    b.Property<int>("num_usr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("bloqueado")
                        .HasColumnType("bit");

                    b.Property<bool>("esAdmin")
                        .HasColumnType("bit");

                    b.HasKey("num_usr");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Final.Models.Reserva", b =>
                {
                    b.HasOne("Final.Models.Usuario", "persona")
                        .WithMany()
                        .HasForeignKey("personanum_usr");

                    b.HasOne("Final.Models.Alojamiento", "propiedad")
                        .WithMany()
                        .HasForeignKey("propiedadpk");
                });
#pragma warning restore 612, 618
        }
    }
}
